name: Continuous Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Deploy to Railway
        run: railway up -- --yes
        working-directory: ${{ github.workspace }}
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

#name: Continuous Deployment
#
#on:
#  push:
#    branches:
#      - master
#
#jobs:
#  deploy:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout code (needed for metadata or future use)
#        uses: actions/checkout@v3
#
#      - name: Deploy to EC2 via SSH
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.SSH_HOST }}
#          username: ${{ secrets.SSH_USERNAME }}
#          key: ${{ secrets.SSH_KEY }}
#          port: ${{ secrets.SSH_PORT }}
#          script: |
#            cd ~/hapi-forum-ci-cd-sec-app
#            git pull origin master
#            npm install
#            npm run migrate up
#            pm2 restart forum-api
